### ISSUE TITLE
pythonfmask

### ISSUE THREAD

**Issue by bendv** [mapbox/rio-cloudmask#1]
Great initiative! If you were not already aware of this, you may want to checkout pythonfmask: http://pythonfmask.org and sourcecode @ https://bitbucket.org/chchrsc/python-fmask

I have been using it for Sentinel-2 imagery since quite recently. The code is running well, but I have not spent alot of time checking the results yet...

**Comment by perrygeo** [comment]
Thanks @bendv. It looks like a very nice implementation but the dependencies don't work with our current system (specifically the `osgeo.gdal` python bindings are problematic).

Would you be interested in collaborating on some shared functions which were liberally licensed and did not depend on a specific IO library (acting on numpy arrays)?

**Comment by bendv** [comment]
Hi @perrygeo, thanks for the reply. I should have been more clear - I am not one of the developers of pythonfmask, but have just starting using it for my own work. I'll send you contact info by email in case you're interested in following up with the developers. Either way, I'm keen to see how your implementation develops.

**Comment by perrygeo** [comment]
The use of osgeo.gdal bindings are a deal breaker at the moment. We'll continue to work towards collaboration with the python-fmask folks as much as we can.
